Repository LinkdropProtocol/linkdrop-monorepo, pull requests merged in 2019-07, with the labels that each got.

#248 Added deploy proxy with signer method
  contracts/contracts/factory/LinkdropFactoryCommon.sol
  contracts/contracts/linkdrop/LinkdropCommon.sol
  contracts/test/DeployWithSigner.js
  yarn.lock
Labels: new feature

#252 Updated SDK
  scripts/src/generate_links_erc20.js
  scripts/src/generate_links_erc721.js
  scripts/src/generate_links_eth.js
  sdk/src/generateLink.js
Labels: new feature

#250 Added ropsten support
  server/deploy/shipitfile.js
  server/package.json
Labels: new feature

#259 Added fix for infura api key
  server/controllers/claimController.js
Labels: bug

#272 Relayer refactor
  .gitignore
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/linkdrop/LinkdropERC20.sol
  contracts/contracts/linkdrop/LinkdropERC721.sol
  contracts/contracts/registry/Registry.sol
  contracts/scripts/utils.js
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC721.js
  package.json
  scripts/src/claim_erc20.js
  scripts/src/claim_erc721.js
  scripts/src/claim_eth.js
  scripts/src/deploy_factory.js
  scripts/src/deploy_mastercopy.js
  scripts/src/deploy_registry.js
  scripts/src/generate_links_erc20.js
  scripts/src/generate_links_erc721.js
  scripts/src/generate_links_eth.js
  sdk/src/generateLink.js
  sdk/src/index.js
  server/controllers/claimController.js
  server/deploy/shipitfile.js
  server/models/claimTx.js
  server/models/claimTxERC721.js
  server/package.json
  server/server.js
  server/src/controllers/claimController.js
  server/src/controllers/lastTxHashController.js
  server/src/models/Operation.js
  server/src/models/Transaction.js
  server/src/models/connectDB.js
  server/src/routes/index.js
  server/src/routes/routes.js
  server/src/services/OperationService.js
  server/src/services/claimService.js
  server/src/services/lastTxHashService.js
  server/src/services/linkdropService.js
  server/src/services/proxyFactoryService.js
  server/src/services/relayerWalletService.js
  server/src/utils/errors.js
  server/src/utils/logger.js
  yarn.lock
Labels: Refactoring

#286 Added additional balance checks to contracts
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/linkdrop/LinkdropERC20.sol
  contracts/contracts/linkdrop/LinkdropERC721.sol
  contracts/contracts/mocks/NFTMock.sol
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC721.js
Labels: new feature

#289 Removed checkClaimParams from Factory
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC20.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC721.sol
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC721.js
Labels: Refactoring, new feature

#297 Rearchitectured contracts
  configs/scripts.config.json.sample
  contracts/contracts/factory/FeeManager.sol
  contracts/contracts/factory/LinkdropFactory.sol
  contracts/contracts/factory/LinkdropFactoryCommon.sol
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/factory/RelayerManager.sol
  contracts/contracts/interfaces/ILinkdropCommon.sol
  contracts/contracts/interfaces/ILinkdropERC20.sol
  contracts/contracts/interfaces/ILinkdropERC721.sol
  contracts/contracts/linkdrop/LinkdropCommon.sol
  contracts/contracts/linkdrop/LinkdropERC20.sol
  contracts/contracts/linkdrop/LinkdropERC721.sol
  contracts/contracts/registry/Registry.sol
  contracts/contracts/storage/LinkdropFactoryStorage.sol
  contracts/contracts/storage/LinkdropStorage.sol
  contracts/test/Campaigns.js
  contracts/test/Factory.js
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC721.js
  contracts/test/Upgradable.js
  scripts/src/claim_erc721.js
  scripts/src/deploy_erc721.js
  scripts/src/deploy_factory.js
  scripts/src/deploy_registry.js
  scripts/src/generate_links_erc20.js
  scripts/src/generate_links_erc721.js
  scripts/src/generate_links_eth.js
Labels: new feature
