Repository LinkdropProtocol/linkdrop-monorepo, pull requests merged in 2019-06, with the labels that each got.

#177 Added upgradability to contracts
  contracts/contracts/factory/CloneFactory.sol
  contracts/contracts/factory/LinkdropFactory.sol
  contracts/contracts/factory/LinkdropFactoryCommon.sol
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC20Approve.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC721Approve.sol
  contracts/contracts/interfaces/ILinkdropCommon.sol
  contracts/contracts/interfaces/ILinkdropERC20.sol
  contracts/contracts/interfaces/ILinkdropERC721.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC20.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC721.sol
  contracts/contracts/interfaces/approve/ILinkdropERC20Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropERC721Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropFactoryERC20Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropFactoryERC721Approve.sol
  contracts/contracts/linkdrop/LinkdropCommon.sol
  contracts/contracts/linkdrop/LinkdropERC20.sol
  contracts/contracts/linkdrop/LinkdropERC721.sol
  contracts/contracts/linkdrop/approve/LinkdropERC20Approve.sol
  contracts/contracts/linkdrop/approve/LinkdropERC721Approve.sol
  contracts/contracts/storage/LinkdropFactoryStorage.sol
  contracts/contracts/storage/LinkdropStorage.sol
  contracts/scripts/computeInitcode.js
  contracts/scripts/utils.js
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC20Approve.js
  contracts/test/LinkdropERC721.js
  contracts/test/LinkdropERC721Approve.js
  contracts/test/Proxy.js
  contracts/test/Upgradable.js
Labels: new feature

#185 Added chain id check
  contracts/contracts/factory/LinkdropFactory.sol
  contracts/contracts/factory/LinkdropFactoryCommon.sol
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC20Approve.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC721Approve.sol
  contracts/contracts/interfaces/ILinkdropCommon.sol
  contracts/contracts/interfaces/ILinkdropERC20.sol
  contracts/contracts/interfaces/ILinkdropERC721.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC20.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC721.sol
  contracts/contracts/interfaces/approve/ILinkdropERC20Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropERC721Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropFactoryERC20Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropFactoryERC721Approve.sol
  contracts/contracts/linkdrop/LinkdropCommon.sol
  contracts/contracts/linkdrop/LinkdropERC20.sol
  contracts/contracts/linkdrop/LinkdropERC721.sol
  contracts/contracts/linkdrop/approve/LinkdropERC20Approve.sol
  contracts/contracts/linkdrop/approve/LinkdropERC721Approve.sol
  contracts/contracts/storage/LinkdropFactoryStorage.sol
  contracts/contracts/storage/LinkdropStorage.sol
  contracts/scripts/utils.js
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC20Approve.js
  contracts/test/LinkdropERC721.js
  contracts/test/LinkdropERC721Approve.js
  contracts/test/Upgradable.js
Labels: new feature

#187 Upgraded SDK and server
  config/scripts.config.json.sample
  scripts/src/claim_erc20.js
  scripts/src/claim_erc721.js
  scripts/src/claim_eth.js
  scripts/src/deploy_factory.js
  scripts/src/index.js
  scripts/src/utils.js
  sdk/src/claim.js
  sdk/src/generateLink.js
  sdk/src/utils.js
  server/controllers/claimController.js
  server/models/claimTx.js
  server/models/claimTxERC721.js
Labels: new feature

#194 Refactored contracts and updated scripts
  contracts/contracts/factory/LinkdropFactory.sol
  contracts/contracts/factory/LinkdropFactoryCommon.sol
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC20Approve.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC721Approve.sol
  contracts/contracts/interfaces/ILinkdropCommon.sol
  contracts/contracts/linkdrop/LinkdropCommon.sol
  contracts/contracts/storage/LinkdropFactoryStorage.sol
  contracts/contracts/storage/LinkdropStorage.sol
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC20Approve.js
  contracts/test/LinkdropERC721.js
  contracts/test/LinkdropERC721Approve.js
  contracts/test/Upgradable.js
  scripts/src/deploy_factory.js
  scripts/src/index.js
  scripts/src/utils.js
Labels: Refactoring, new feature

#207 Added new styling, refactoring
  README.md
  configs/demo.config.json
  configs/index.js
  configs/scripts.config.json.sample
  configs/server.config.json.sample
  contracts/contracts/linkdrop/LinkdropERC721.sol
  scripts/README.md
  scripts/package.json
  scripts/src/claim_erc20.js
  scripts/src/claim_erc721.js
  scripts/src/claim_eth.js
  scripts/src/deploy_erc20.js
  scripts/src/deploy_erc721.js
  scripts/src/deploy_factory.js
  scripts/src/deploy_mastercopy.js
  scripts/src/generate_links_erc20.js
  scripts/src/generate_links_erc721.js
  scripts/src/generate_links_eth.js
  scripts/src/index.js
  scripts/src/utils.js
  sdk/src/claim.js
  sdk/src/generateLink.js
  server/controllers/claimController.js
  server/package.json
  server/server.js
  yarn.lock
Labels: Refactoring, new feature

#210 Added fix for the frontend
  sdk/src/claim.js
  sdk/src/generateLink.js
  server/controllers/claimController.js
Labels: bug

#218 added fix for prod with web3 obj and isApprove fix
  apps/app-claim/components/pages/main/claiming-process-page/index.js
  apps/app-claim/data/actions/tokens.js
  apps/app-claim/data/store/saga/tokens/every/claim-tokens-erc20.js
  apps/app-claim/data/store/saga/tokens/every/claim-tokens-erc721.js
  apps/app-demo/components/pages/main/link-share/index.js
Labels: bug
