Repository LinkdropProtocol/linkdrop-monorepo, pull requests merged in 2019-05, with the labels that each got.

#98 Dev gitignore fix
  .gitignore
  README.md
  app-claim/.gitignore
  app-claim/assets/images/coinbase.png
  app-claim/assets/images/coinbase@2x.png
  app-claim/assets/images/opera.png
  app-claim/assets/images/opera@2x.png
  app-claim/assets/images/status.png
  app-claim/assets/images/status@2x.png
  app-claim/components/pages/main/wallet-choose-page/slider/index.js
  app-landing/.gitignore
  app-landing/assets/images/coinbase.png
  app-landing/assets/images/coinbase@2x.png
  app-landing/assets/images/opera.png
  app-landing/assets/images/opera@2x.png
  app-landing/components/pages/main/trusted-by/index.js
  app-landing/data/api/tokens/get-tokens-opensea.js
  config/wallets.js
  linkdrop-ui-kit/.gitignore
Labels: documentation

#106 changes for host split
  app-claim/data/store/saga/tokens/every/claim-tokens-erc20.js
  app-claim/data/store/saga/tokens/every/claim-tokens-erc721.js
  app-landing/data/store/saga/user/every/generate-link-erc20.js
  app-landing/data/store/saga/user/every/generate-link-erc721.js
Labels: new feature

#118 Changed factory contract
  contracts/contracts/Factory.sol
  contracts/contracts/LinkdropERC721.sol
  contracts/test/Linkdrop.js
  contracts/test/LinkdropERC721.js
Labels: new feature

#130 Added server CI/CD
  server/README.md
  server/deploy/package.json
  server/deploy/shipitfile.js
  server/deploy/yarn.lock
  server/package.json
Labels: infrastructure

#153 added modal window, new network, improvements for design, wallet choo…
  app-claim/components/pages/main/error-page/index.js
  app-claim/components/pages/main/error-page/styles.module.scss
  app-claim/components/pages/main/index.js
  app-claim/components/pages/main/wallet-choose-page/common-instruction/index.js
  app-claim/components/pages/main/wallet-choose-page/index.js
  app-claim/data/store/saga/tokens/every/claim-tokens-erc20.js
  app-claim/helpers/get-wallet-link/index.js
  app-claim/texts/en/pages/main/index.js
  app-landing/components/common/header/index.js
  app-landing/components/common/header/styles.module.scss
  app-landing/components/pages/common/link-block/index.js
  app-landing/components/pages/main/final-screen/index.js
  app-landing/components/pages/main/index.js
  app-landing/components/pages/main/link-share/index.js
  app-landing/components/pages/main/pro-solution/index.js
  app-landing/components/pages/main/pro-solution/styles.module.scss
  app-landing/components/pages/main/styles.module.scss
  app-landing/components/pages/main/tokens-send/index.js
  app-landing/data/actions/tokens.js
  app-landing/data/store/saga/tokens/every/get-tokens-data.js
  app-landing/texts/en/components/footer/index.js
  app-landing/texts/en/components/header/index.js
  app-landing/texts/en/pages/main/index.js
  config/wallets.js
  linkdrop-ui-kit/index.js
  linkdrop-ui-kit/src/index.js
  linkdrop-ui-kit/src/modal-window/index.js
  linkdrop-ui-kit/src/modal-window/styles.module.scss
Labels: bug, design, new feature

#164 Added logic for separate signing keys
  contracts/contracts/factory/LinkdropFactory.sol
  contracts/contracts/factory/LinkdropFactoryCommon.sol
  contracts/contracts/factory/LinkdropFactoryERC20.sol
  contracts/contracts/factory/LinkdropFactoryERC721.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC20Approve.sol
  contracts/contracts/factory/approve/LinkdropFactoryERC721Approve.sol
  contracts/contracts/interfaces/ILinkdropCommon.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC20.sol
  contracts/contracts/interfaces/ILinkdropFactoryERC721.sol
  contracts/contracts/interfaces/approve/ILinkdropERC20Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropERC721Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropFactoryERC20Approve.sol
  contracts/contracts/interfaces/approve/ILinkdropFactoryERC721Approve.sol
  contracts/contracts/linkdrop/LinkdropCommon.sol
  contracts/contracts/linkdrop/LinkdropERC20.sol
  contracts/contracts/linkdrop/LinkdropERC721.sol
  contracts/contracts/linkdrop/LinkdropMastercopy.sol
  contracts/contracts/linkdrop/approve/LinkdropERC20Approve.sol
  contracts/contracts/linkdrop/approve/LinkdropERC721Approve.sol
  contracts/contracts/storage/LinkdropStorage.sol
  contracts/test/LinkdropERC20.js
  contracts/test/LinkdropERC20Approve.js
  contracts/test/LinkdropERC721.js
  contracts/test/LinkdropERC721Approve.js
  contracts/test/Proxy.js
Labels: new feature

#169 Updated SDK, scripts and server to support `approve` pattern
  config/scripts.config.json.sample
  scripts/src/claim_erc20.js
  scripts/src/claim_erc721.js
  scripts/src/claim_eth.js
  scripts/src/generate_links_erc20.js
  scripts/src/generate_links_erc721.js
  scripts/src/generate_links_eth.js
  scripts/src/index.js
  sdk/src/claim.js
  sdk/src/generateLink.js
  server/controllers/claimController.js
  server/models/claimTx.js
  server/models/claimTxERC721.js
Labels: new feature
